name: deploy flutter web to github pages

on:
  push:
    branches: ["master"]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2
      # https://github.com/marketplace/actions/flutter-action
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: 캐시된 빌드, Pub 초기화
        run: flutter clean
      - name: Pub 새로 가져오기
        run: flutter pub get
      - name: 플러터 웹 빌드
        run: flutter build web --base-href "/stockmanager/"
      - name: Github Pages 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: web
          publish_dir: ./build/web

#      - run: git config user.name github-actions
#      - run: git config user.email github-actions@github.com
#      - run: git --work-tree build/web add --all
#      - run: git commit -m "Automatic deployment by github-actions"
#      - run: git push origin HEAD:gh_pages --force